apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizdesk
  labels:
    app: wizdesk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wizdesk
  template:
    metadata:
      labels:
        app: wizdesk
    spec:
      containers:
      - name: wizdesk
        image: ramyaravishabr/wizdesk:latest
        ports:
        - containerPort: 3000
